DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'object_geometry'
    ) THEN
        RAISE NOTICE 'object_geometry does not exist, migration skipped';
        RETURN;
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.object_geometry_changes
(
    id_object_geometry_change bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_type integer NOT NULL,
    object_id integer NOT NULL,
    change_operation character(1) NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT chk_object_geometry_changes_op
        CHECK (change_operation IN ('I', 'U', 'D'))
);

CREATE INDEX IF NOT EXISTS idx_object_geometry_changes_changed_at
    ON public.object_geometry_changes (changed_at);

CREATE INDEX IF NOT EXISTS idx_object_geometry_changes_object
    ON public.object_geometry_changes (object_type, object_id);

CREATE TABLE IF NOT EXISTS public.object_geometry_history
(
    id_object_geometry_history bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_object_geometry bigint,
    object_type integer NOT NULL,
    object_id integer NOT NULL,
    geometry_role character varying(50) NOT NULL,
    geometry_type character varying(20) NOT NULL,
    id_coordinates integer NOT NULL,
    point_order integer NOT NULL,
    is_closed boolean NOT NULL,
    row_created_at timestamp without time zone,
    row_updated_at timestamp without time zone,
    change_operation character(1) NOT NULL,
    changed_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT chk_object_geometry_history_op
        CHECK (change_operation IN ('I', 'U', 'D'))
);

CREATE INDEX IF NOT EXISTS idx_object_geometry_history_object
    ON public.object_geometry_history (object_type, object_id, changed_at);

CREATE OR REPLACE FUNCTION public.fn_object_geometry_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS trg_object_geometry_touch_updated_at ON public.object_geometry;

CREATE TRIGGER trg_object_geometry_touch_updated_at
BEFORE UPDATE ON public.object_geometry
FOR EACH ROW
EXECUTE FUNCTION public.fn_object_geometry_touch_updated_at();

CREATE OR REPLACE FUNCTION public.fn_object_geometry_log_change()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
DECLARE
    v_object_type integer;
    v_object_id integer;
    v_change_op character(1);
BEGIN
    IF TG_OP = 'INSERT' THEN
        v_object_type := NEW.object_type;
        v_object_id := NEW.object_id;
        v_change_op := 'I';
    ELSIF TG_OP = 'UPDATE' THEN
        v_object_type := NEW.object_type;
        v_object_id := NEW.object_id;
        v_change_op := 'U';
    ELSE
        v_object_type := OLD.object_type;
        v_object_id := OLD.object_id;
        v_change_op := 'D';
    END IF;

    INSERT INTO public.object_geometry_changes (object_type, object_id, change_operation)
    VALUES (v_object_type, v_object_id, v_change_op);

    IF TG_OP = 'INSERT' THEN
        INSERT INTO public.object_geometry_history
        (
            id_object_geometry, object_type, object_id, geometry_role, geometry_type,
            id_coordinates, point_order, is_closed,
            row_created_at, row_updated_at, change_operation
        )
        VALUES
        (
            NEW.id_object_geometry, NEW.object_type, NEW.object_id, NEW.geometry_role, NEW.geometry_type,
            NEW.id_coordinates, NEW.point_order, NEW.is_closed,
            NEW.created_at, NEW.updated_at, 'I'
        );
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO public.object_geometry_history
        (
            id_object_geometry, object_type, object_id, geometry_role, geometry_type,
            id_coordinates, point_order, is_closed,
            row_created_at, row_updated_at, change_operation
        )
        VALUES
        (
            NEW.id_object_geometry, NEW.object_type, NEW.object_id, NEW.geometry_role, NEW.geometry_type,
            NEW.id_coordinates, NEW.point_order, NEW.is_closed,
            NEW.created_at, NEW.updated_at, 'U'
        );
    ELSE
        INSERT INTO public.object_geometry_history
        (
            id_object_geometry, object_type, object_id, geometry_role, geometry_type,
            id_coordinates, point_order, is_closed,
            row_created_at, row_updated_at, change_operation
        )
        VALUES
        (
            OLD.id_object_geometry, OLD.object_type, OLD.object_id, OLD.geometry_role, OLD.geometry_type,
            OLD.id_coordinates, OLD.point_order, OLD.is_closed,
            OLD.created_at, OLD.updated_at, 'D'
        );
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS trg_object_geometry_log_change ON public.object_geometry;

CREATE TRIGGER trg_object_geometry_log_change
AFTER INSERT OR UPDATE OR DELETE ON public.object_geometry
FOR EACH ROW
EXECUTE FUNCTION public.fn_object_geometry_log_change();
