CREATE TABLE IF NOT EXISTS public.object_geometry
(
    id_object_geometry bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_type integer NOT NULL,
    object_id integer NOT NULL,
    geometry_role character varying(50) NOT NULL,
    geometry_type character varying(20) NOT NULL,
    id_coordinates integer NOT NULL,
    point_order integer NOT NULL,
    is_closed boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT fk_object_geometry_coordinates
        FOREIGN KEY (id_coordinates)
        REFERENCES public.coordinates (id_coordinates)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_object_geometry_object
    ON public.object_geometry (object_type, object_id);

CREATE INDEX IF NOT EXISTS idx_object_geometry_role
    ON public.object_geometry (object_type, object_id, geometry_role);

CREATE UNIQUE INDEX IF NOT EXISTS uq_object_geometry_point
    ON public.object_geometry (object_type, object_id, geometry_role, point_order);
